### ISSUE TITLE
create-scheduler-task with lambda?

### ISSUE THREAD

**Issue by atgreen** [sharplispers/scheduler#1]
Thank you for sharing this great package!

Have you ever considered making a create-scheduler-task that takes a callback lambda instead of providing the s-expression in text? I would find that useful.

Also, I do see that you are licensing it under a BSD 2-clause license.  For the avoidance of any doubt, it would be nice if you were to include the license text in the repo.

Regardless, I appreciate your efforts and for making this FOSS!

Thank you!

**Comment by dkochmanski** [comment]
If I remember right, the commands are specified as text to make it easy to store them in a database or file (don't take my word for that - I didn't work on this project for quite a while); having a real data in there would make the format not suitable for text.

That said, all you have to do is define a new method

```
(defclass my-task (task) ())
(defmethod update-scheduler-task …) ;; check that the command is a function, fallback to (lambda () (eval (read-from-string …))) for strings
(defmethod execute-task ((task my-task))
  (funcall (task-command task)))

```

well, I did not run it and there are probably more places to fix, however this should
give you an idea how to provide something that is not based on text. The function start-scheduler
have a bug, instead of calling eval for the active-task? cond branch it should call execute-task.

```
(create-scheduler-task scheduler (make-instance 'my-task :time-specs specs :command lambda ...))
```

**Comment by dkochmanski** [comment]
I've pushed a few cleanups:
- added a license file
- added a missing dependency
- implemented the lambda-task

As of the lambda task, instead of specifying all as a string, you may add a function now:

```
(scheduler:create-scheduler-task *scheduler*
   (cons "* * * * *" (lambda () (print :minute))))
```
